=== wgawel/clarin-pl-dspace/dspace/config/input-forms.dtd
<!-- DSpace Custom Submit input form definition language -->


 <!ELEMENT input-forms (form-map, form-definitions, form-definitions-extra, form-value-pairs, form-complex-definitions) >

 <!ELEMENT form-map (name-map)* >
 <!ELEMENT name-map EMPTY >
 <!ATTLIST name-map 
           collection-handle CDATA #REQUIRED
           form-name NMTOKEN #REQUIRED>

 <!ELEMENT form-definitions (form)+ >
 <!ELEMENT form-definitions-extra (form)+ >
 <!ELEMENT form-complex-definitions (definition)+ >
 <!ELEMENT form (page)+ >
 <!ATTLIST form name NMTOKEN #REQUIRED>
 <!ELEMENT page (field)+ >
 <!ATTLIST page number NMTOKEN #REQUIRED>
 <!ELEMENT field (dc-schema, dc-element, dc-qualifier?, repeatable?, visibility?,
         repeatable-component?, repeatable-parse?,
         mapped-to?, label, type-bind?, input-type, hint, autocomplete?, required?, placeholder?,
         vocabulary?, regexp?, regexp-warning?, additional?, component-label?, collapsible?, acl?, class?) >
 <!ELEMENT definition (input*) >
 <!ATTLIST definition
        name CDATA #REQUIRED
        >

 <!ELEMENT dc-schema (#PCDATA) >
 <!ELEMENT dc-element (#PCDATA) >
 <!ELEMENT dc-qualifier (#PCDATA) >
 <!ELEMENT type-bind (#PCDATA) >
 <!ATTLIST type-bind field CDATA #IMPLIED >
 
 <!ELEMENT repeatable (#PCDATA) >
 <!ELEMENT repeatable-component (#PCDATA) >
 <!ELEMENT repeatable-parse (#PCDATA) >
 <!ELEMENT autocomplete (#PCDATA) >
 <!ELEMENT mapped-to (#PCDATA) >
 <!ELEMENT label (#PCDATA) >
 <!ELEMENT additional (#PCDATA) >
 <!ELEMENT component-label (#PCDATA) >
 <!ELEMENT collapsible (#PCDATA) >
 <!ELEMENT input-type (#PCDATA)>

 <!ELEMENT input (#PCDATA) >
 <!ATTLIST input type CDATA #REQUIRED >
 <!ATTLIST input name CDATA #REQUIRED >
 <!ATTLIST input label CDATA #IMPLIED >
 <!ATTLIST input regexp CDATA #IMPLIED >
 <!ATTLIST input pairs CDATA #IMPLIED >
 <!ATTLIST input help CDATA #IMPLIED >
 <!ATTLIST input autocomplete CDATA #IMPLIED >
 <!ATTLIST input placeholder CDATA #IMPLIED >
 <!ATTLIST input id CDATA #IMPLIED >
 <!ATTLIST input class CDATA #IMPLIED >
 <!ATTLIST input readonly CDATA #IMPLIED >
 <!ATTLIST input mapped-to-if-not-default CDATA #IMPLIED >
 <!ATTLIST input value CDATA #IMPLIED >
 <!ATTLIST input required CDATA #IMPLIED >

 <!ELEMENT hint (#PCDATA) >
 <!ELEMENT required (#PCDATA)>

 <!ELEMENT form-value-pairs (value-pairs)* >
 <!ELEMENT value-pairs (pair)+ >

 <!-- will be used in  String.matches, so mind proper escaping -->
 <!ELEMENT regexp (#PCDATA) >
 <!ELEMENT regexp-warning (#PCDATA) >

 <!ELEMENT placeholder (#PCDATA) >

 <!--
      ACL element for fine-grained access control 
      the content should be semicolon separated list of entries in format matching the following regexp:
      policy=(allow|deny),action=(read|write),grantee-type=(user|group),grantee-id=(\d+,\*) 
 -->
 <!ELEMENT acl (#PCDATA)>
 <!ELEMENT class (#PCDATA) >
 
 <!-- ***
        To assign a particular 'value-pairs' list to a particular dropdown 'input-type'
        field, as found on a particular form, put:
        - value-pairs/@value-pairs-name string into
           form/page/field/input-type/@value-pairs-name
        - form/page/field/@DCelement + '_' + form/field/DCqualifier into
           value-pairs/@dc-term
             (e.g. 'language_iso')
  -->
 <!ATTLIST value-pairs value-pairs-name CDATA #REQUIRED
                            dc-term   CDATA #REQUIRED
 >
  
 <!ELEMENT pair (displayed-value,stored-value) >
 <!ELEMENT displayed-value (#PCDATA)>
 <!ELEMENT stored-value (#PCDATA)>

 <!ATTLIST input-type value-pairs-name CDATA  #IMPLIED>

 <!ATTLIST input-type complex-definition-ref CDATA  #IMPLIED>

 <!ELEMENT vocabulary (#PCDATA) >

 <!ATTLIST vocabulary closed (true|false) "false"> 

 <!ELEMENT visibility (#PCDATA) >

=== wgawel/clarin-pl-dspace/dspace/config/input-forms.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE input-forms SYSTEM "input-forms.dtd">
<input-forms>
    <!-- The form-map maps collection handles to forms. DSpace does not       -->
    <!-- require a collection name to be unique, not even within a community. -->
    <!-- DSpace does however ensure that each collection's handle is unique.  -->
    <!-- Form-map provides the means to associate a unique collection name    -->
    <!-- with a form. The form-map also provides the special handle "default" -->
    <!-- (which is never a collection), here mapped to "traditional". Any     -->
    <!-- collection which does not appear in this map will be associated with -->
    <!-- the mapping for handle "default".                                    -->

    <form-map>
        <name-map collection-handle="default" form-name="traditional"/>
        <!-- TODO real handle -->
        <name-map collection-handle="123456789/2" form-name="clariah_submissions"/>
    </form-map>


    <!-- The form-definitions map lays out the detailed definition of all the -->
    <!-- submission forms. Each separate form set has a unique name as an     -->
    <!-- attribute. This name matches one of the names in the form-map. One   -->
    <!-- named form set has the name "traditional"; as this name suggests,    -->
    <!-- it is the old style and is also the default, which gets used when    -->
    <!-- the specified collection has no correspondingly-named form set.      -->
    <!--                                                                      -->
    <!-- Each form set contains an ordered set of pages; each page defines    -->
    <!-- one submission metadata entry screen. Each page has an ordered list  -->
    <!-- of field definitions, Each field definition corresponds to one       -->
    <!-- metatdata entry (a so-called row), which has a DC element name, a    -->
    <!-- displayed label, a text string prompt which is called a hint, and    -->
    <!-- an input-type. Each field also may hold optional elements: DC        -->
    <!-- qualifier name, a repeatable flag, and a text string whose presence  -->
    <!-- serves as a 'this field is required' flag.                           -->

    <form-definitions>

        <form name="traditional">
            <page number="1">

                <!-- Basic info
                        +type for type binds
                        title
                      projectUrl
                      demoUrl
                        date
                        +admin only fields-->

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>type</dc-element>
                    <dc-qualifier/>
                    <repeatable>false</repeatable>
                    <label>input_forms.field.dc.type.label</label>
                    <input-type value-pairs-name="common_types">dropdown</input-type>
                    <hint>input_forms.field.dc.type.hint</hint>
                    <required>input_forms.field.dc.type.required</required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier/>
                    <repeatable>false</repeatable>
                    <label>input_forms.field.dc.title.label</label>
                    <input-type>onebox</input-type>
                    <hint>input_forms.field.dc.title.hint</hint>
                    <required>input_forms.field.dc.title.required</required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>source</dc-element>
                    <dc-qualifier>uri</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>input_forms.field.dc.source.uri.label</label>
                    <input-type>onebox</input-type>
                    <hint>input_forms.field.dc.source.uri.hint</hint>
                    <required/>
                    <regexp>http.*</regexp>
                    <regexp-warning>input_forms.field.dc.source.uri.regexp-warning</regexp-warning>
                </field>

                <field>
                    <dc-schema>local</dc-schema>
                    <dc-element>demo</dc-element>
                    <dc-qualifier>uri</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>input_forms.field.local.demo.uri.label</label>
                    <input-type>onebox</input-type>
                    <hint>input_forms.field.local.demo.uri.hint</hint>
                    <required/>
                    <regexp>http.*</regexp>
                    <regexp-warning>input_forms.field.local.demo.uri.regexp-warning</regexp-warning>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>relation</dc-element>
                    <dc-qualifier>isreferencedby</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>input_forms.field.dc.relation.isreferencedby.label</label>
                    <input-type>onebox</input-type>
                    <hint>input_forms.field.dc.relation.isreferencedby.hint</hint>
                    <required/>
                    <regexp>http.*</regexp>
                    <regexp-warning>input_forms.field.dc.relation.isreferencedby.regexp-warning</regexp-warning>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>date</dc-element>
                    <dc-qualifier>issued</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>input_forms.field.dc.date.issued.label</label>
                    <input-type>FormattedDate</input-type>
                    <hint>input_forms.field.dc.date.issued.hint</hint>
                    <required>input_forms.field.dc.date.issued.required</required>
                    <class>with-datepicker</class>
                </field>

                <field>
                    <dc-schema>local</dc-schema>
                    <dc-element>hidden</dc-element>
                    <dc-qualifier/>
                    <repeatable>false</repeatable>
                    <label>input_forms.field.local.hidden.label</label>
                    <input-type value-pairs-name="hidden_list">list</input-type>
                    <hint>input_forms.field.local.hidden.hint</hint>
                    <required/>
                    <acl>
                        policy=deny,action=read,grantee-type=user,grantee-id=*
                    </acl>
                </field>

                <field>
                    <dc-schema>local</dc-schema>
                    <dc-element>hasMetadata</dc-element>
                    <dc-qualifier/>
                    <repeatable>false</repeatable>
                    <label>input_forms.field.local.hasMetadata.label</label>
                    <input-type value-pairs-name="metashare_languageDependent">list</input-type>
                    <!-- true/false value -->
                    <hint>input_forms.field.local.hasMetadata.hint</hint>
                    <required/>
                    <acl>
                        policy=deny,action=read,grantee-type=user,grantee-id=*
                    </acl>
                </field>

            </page>

            <page number="2">

                <!-- who's involved
                        authors
                        publisher
                        funding
                        contact
                -->


                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>contributor</dc-element>
                    <dc-qualifier>author</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>input_forms.field.dc.contributor.author.label</label>
                    <input-type>name</input-type>
                    <hint>input_forms.field.dc.contributor.author.hint</hint>
                    <autocomplete>solr-author_ac-specific</autocomplete>
                    <required>input_forms.field.dc.contributor.author.required</required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>publisher</dc-element>
                    <dc-qualifier/>
                    <repeatable>true</repeatable>
                    <label>input_forms.field.dc.publisher.label</label>
                    <input-type>onebox</input-type>
                    <hint>input_forms.field.dc.publisher.hint</hint>
                    <autocomplete>solr-publisher_ac</autocomplete>
                    <required>input_forms.field.dc.publisher.required</required>
                </field>

                <field>
                    <dc-schema>local</dc-schema>
                    <dc-element>contact</dc-element>
                    <dc-qualifier>person</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>input_forms.field.local.contact.person.label</label>
                    <input-type complex-definition-ref="contact_person">complex</input-type>
                    <hint>input_forms.field.local.contact.person.hint</hint>
                    <required>input_forms.field.local.contact.person.required</required>
                </field>


                <field>
                    <dc-schema>local</dc-schema>
                    <dc-element>sponsor</dc-element>
                    <repeatable>true</repeatable>
                    <label>input_forms.field.local.sponsor.label</label>
                    <input-type complex-definition-ref="funding">complex</input-type>
                    <hint>input_forms.field.local.sponsor.hint</hint>
                </field>


            </page>

            <page number="3">
                <!-- describe the resource -->
